// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAANLI6R9fU5ex_VKqWS_MVRfQvTdftj8o',
    appId: '1:123413467414:web:02a11f1e9f84af7c1e8037',
    messagingSenderId: '123413467414',
    projectId: 'obsidia-copycat',
    authDomain: 'obsidia-copycat.firebaseapp.com',
    storageBucket: 'obsidia-copycat.appspot.com',
    measurementId: 'G-3FVMTPXT0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjlEwdSDc3t8Q5g5zriUJF85s-ZR3n6Tc',
    appId: '1:123413467414:android:6fbfb0b866a76dd61e8037',
    messagingSenderId: '123413467414',
    projectId: 'obsidia-copycat',
    storageBucket: 'obsidia-copycat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHmn9lmZwOhEqjW70VQwcRdY_2FoDgoo',
    appId: '1:123413467414:ios:ea75ec8951cc6d9d1e8037',
    messagingSenderId: '123413467414',
    projectId: 'obsidia-copycat',
    storageBucket: 'obsidia-copycat.appspot.com',
    iosBundleId: 'com.example.obsydiaCopy1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHmn9lmZwOhEqjW70VQwcRdY_2FoDgoo',
    appId: '1:123413467414:ios:ea75ec8951cc6d9d1e8037',
    messagingSenderId: '123413467414',
    projectId: 'obsidia-copycat',
    storageBucket: 'obsidia-copycat.appspot.com',
    iosBundleId: 'com.example.obsydiaCopy1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAANLI6R9fU5ex_VKqWS_MVRfQvTdftj8o',
    appId: '1:123413467414:web:e13958ef1ce9340b1e8037',
    messagingSenderId: '123413467414',
    projectId: 'obsidia-copycat',
    authDomain: 'obsidia-copycat.firebaseapp.com',
    storageBucket: 'obsidia-copycat.appspot.com',
    measurementId: 'G-VQHMLDNMDG',
  );
}
